name: FeatureGuard CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run CLI demo scan
      run: npm run start:cli

    - name: Run Backend sanity check
      run: |
        node backend.js &
        sleep 3
        echo "Backend started successfully."

    - name: Run Dashboard sanity check
      run: |
        node dashboard.js &
        sleep 3
        echo "Dashboard started successfully."

