name: FeatureGuard CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Root Dependencies
        run: npm install

      - name: Install Subfolder Dependencies
        run: |
          cd cli && npm install
          cd ../ide-plugin && npm install
          cd ../dashboard && npm install
          cd ../backend && npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

